### ISSUE TITLE
渐变色无效

### ISSUE THREAD

**Issue by q172107875** [jenly1314/CircleProgressView#3]
渐变颜色无效Color.argb无效，6位8位色值都无效，只能是绿色

**Comment by jenly1314** [comment]
请确认你使用的方式正确：
在CircleProgressView初始化后自动测量所占宽高后设置渐变色，即onMeasure方法自调用之后才通过circleProgressView.setProgressColor(int... colors)设置渐变色，详情请参照app中的demo
