### ISSUE TITLE
渐变色

### ISSUE THREAD

**Issue by dd9000901** [jenly1314/CircleProgressView#4]
希望修改一下提供渐变色的方法。如果传入一个数组弄出来的效果不是很理想。可以考虑传入两个数值然后系统加载渐变色。

**Comment by jenly1314** [comment]
效果理不理想取决于你传的色值，一个好看的渐变色应该是渐变均匀的，最好保持首尾呼应，（即首尾色值相同）。对于 **SweepGradient**而言，我能想象到：传两个色值的渐变色，在首尾交汇处会有明显的色值差。建议你传三个渐变色值以上，首尾相同，效果会好很多。

**Comment by HeroGentry** [comment]
发自我的荣耀手机-------- 原始邮件 --------发件人： 黑色幽默 ***@***.***>日期： 2019年12月4日周三 19:32收件人： jenly1314/CircleProgressView ***@***.***>抄送： Subscribed ***@***.***>主    题： [jenly1314/CircleProgressView] 渐变色 (#4)希望修改一下提供渐变色的方法。如果传入一个数组弄出来的效果不是很理想。可以考虑传入两个数值然后系统加载渐变色。
