### ISSUE TITLE
通过showAnimation开始的动画可以取消吗？

### ISSUE THREAD

**Issue by luern0313** [jenly1314/CircleProgressView#6]

**Comment by HeroGentry** [comment]
发自我的荣耀手机-------- 原始邮件 --------发件人： "github-actions[bot]" ***@***.***>日期： 2024年6月27日周四 00:14收件人： jenly1314/CircleProgressView ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [jenly1314/CircleProgressView] 通过showAnimation开始的动画可以取消吗？ (#6)
Closed #6 as completed.
